import type { Metadata } from "next";
import { GeistSans } from 'geist/font/sans'; // Correct import
import { GeistMono } from 'geist/font/mono';   // Correct import
import "./globals.css";
import Header from '@/components/Header'; // Assuming this component exists

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    // This is the correct way to apply the fonts
    <html lang="en" className={`${GeistSans.variable} ${GeistMono.variable}`}>
      <body>
        <Header /> {/* Your Header component */}
        {children}
      </body>
    </html>
  );
}